critic_lr: 1e-3
actor_lr: 1e-4
gamma: 0.99
tau: 0.005

# Pendulum-v1
env: "Pendulum-v1"


policy_noise: 0.2
exploration_noise: 0.1
noise_clip: 0.5

delay_freq: 2


buffer_size: 100000
number_of_episodes: 2000
batch_size: 64


render: True
render_every: 10
save_freq: 10
seed: None

load_model_for_train: False

actor_model: td3_actor.pth
critic_model: td3_critic.pth