timesteps_per_batch: 4800
max_timesteps_per_episode: 1600
n_updates_per_iteration: 5
lr: 1e-3
gamma: 0.99
clip: 0.2

render: True
render_every: 10
save_freq: 10
seed: None

hidden_space: 64

actor_model: models/ppo_actor.pth
critic_model: models/ppo_critic.pth