critic_lr: 1e-3
actor_lr: 1e-4
gamma: 0.99
tau: 1e-3

# Pendulum-v1, LunarLander-v2
env: "Pendulum-v1"

buffer_size: 100000
number_of_episodes: 2000
batch_size: 32


render: True
render_every: 10
save_freq: 10
seed: None

load_model_for_train: False

actor_model: ddpg_actor.pth
critic_model: ddpg_critic.pth